services:
    smo-db:
        image: postgres:15
        container_name: smo-db
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=smo
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: unless-stopped

    smo-web:
        build: .
        container_name: smo-web
        ports:
            - '8000:8000'
        env_file:
            - ./config/flask.env
        volumes:
            # Mount your local .kube directory into the container
            - ~/.kube:/root/.kube:ro
        depends_on:
            - smo-db
        restart: unless-stopped

volumes:
    postgres_data:
