{{- if eq ((.Values.voDescriptorOverwrite.databaseConfig).timeseriesDb).influxDB "enabled" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-wotpy-influxdb
  labels:
    app: {{ .Chart.Name }}-wotpy-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-wotpy-influxdb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-wotpy-influxdb
    spec:
      containers:
        - name: {{ .Chart.Name }}-wotpy-influxdb
          image: influxdb:2.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8086
          env:
            {{- range $v := .Values.voChartOverwrite.influxdb.env }}
            - name: {{ $v.name }}
              value: {{ $v.value }}
            {{- end }}
          resources:
            {{- toYaml .Values.voChartOverwrite.influxdb.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-wotpy-influxdb
  labels:
    app: {{ .Chart.Name }}-wotpy-influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: influx
  selector:
    app: {{ .Chart.Name }}-wotpy-influxdb
{{- end }}
