apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: {{ .Chart.Name }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Chart.Name }}-export
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: {{ .Chart.Name }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.voChartOverwrite.clustersAffinity }}
        - {{ . }}
        {{- end }}
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: {{ .Chart.Name }}
spec:
  type: ClusterSetIP
  ports:
  - port: {{ .Values.voDescriptorOverwrite.catalogue }}
    protocol: TCP
  {{- if .Values.voDescriptorOverwrite.bindingNB.ports.httpPort }}
  - port: {{ .Values.voDescriptorOverwrite.bindingNB.ports.httpPort }}
    protocol: TCP
  {{- end }}
  {{- if .Values.voDescriptorOverwrite.bindingNB.ports.coapPort }}
  - port: {{ .Values.voDescriptorOverwrite.bindingNB.ports.coapPort }}
    protocol: UDP
  {{- end }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .Chart.Name }}-import
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: {{ .Chart.Name }}
  placement:
    clusterAffinity:
      clusterNames:
        {{- range .Values.voChartOverwrite.serviceImportClusters }}
        - {{ . }}
        {{- end }}
