{{- if .Values.voChartOverwrite.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vo.serviceAccountName" . }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.voChartOverwrite.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

